returntocorp/pfff

lang_python/parsing/parser_python.mly, tests/python/parsing/with_stmt.py
A more low-touch attempt to support complex with statements by nesting
multiple simple with statements.
=> Support complex with statements using nested simple with statements

tests/java/java8/Default.java, tests/java/java8/DefaultNested.java, tests/java/java8/Lambda.java, tests/java/java8/Lambda2.java, tests/java/java8/LambdaCompare.java, tests/java/java8/LambdaFunctions.java, tests/java/java8/LambdaFunctions2.java, tests/java/java8/LambdaFunctions3.java, tests/java/java8/LambdaFunctions4.java, tests/java/java8/LambdaFunctions5.java, tests/java/java8/LambdaFunctions6.java, tests/java/java8/LambdaFunctions7.java, tests/java/java8/LambdaFunctions8.java, tests/java/java8/LambdaFunctions9.java, tests/java/java8/List.java, tests/java/java8/MethodReference.java, tests/java/java8/MethodReferenceStatic.java, tests/java/java8/Static.java
Adding a new directory containing tests specific to Java 8 syntax in order to better verify the parse rate of the pfff Java parser
=> Adding tests for Java 8

lang_python/parsing/parser_python.mly
This should help https://github.com/returntocorp/sgrep/issues/29
Test plan:
$ ~/pfff/pfff_test -dump_generic less_attributes.py
Pr(
[DefStmt(
({name=("foo", ());
attrs=[OtherAttribute(OA_Expr,
[E(
Call(
Name(
(("alpha", ()),
{name_qualifier=None; name_typeargs=None; }),
{id_resolved=Ref(None); id_type=Ref(None); }), [
]))]);
...
=> * lang_python/parsing/parser_python.mly: adding attribute in AST

h_program-lang/ast_generic.ml, lang_GENERIC/parsing/map_ast.ml, lang_GENERIC/parsing/meta_ast.ml, lang_GENERIC/parsing/visitor_ast.ml, lang_c/analyze/c_to_generic.ml, lang_go/analyze/go_to_generic.ml, lang_java/analyze/java_to_generic.ml, lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/graph_code_js.ml, lang_js/analyze/graph_code_js.mli, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/meta_ast_js.ml, lang_js/analyze/transpile_js.ml, lang_js/analyze/transpile_js.mli, lang_js/analyze/visitor_ast_js.ml, lang_ml/analyze/ml_to_generic.ml, lang_python/analyze/python_to_generic.ml
this should also help This should help https://github.com/returntocorp/sgrep/issues/29
=> uintroduce intermediate attribute KeywordAttr and add token information

h_program-lang/ast_generic.ml, lang_GENERIC/analyze/lrvalue.ml, lang_GENERIC/parsing/map_ast.ml, lang_GENERIC/parsing/meta_ast.ml, lang_GENERIC/parsing/visitor_ast.ml, lang_python/analyze/python_to_generic.ml, lang_python/parsing/ast_python.ml, lang_python/parsing/meta_ast_python.ml, lang_python/parsing/parser_python.mly, lang_python/parsing/visitor_python.ml
This will help https://github.com/returntocorp/sgrep/issues/49
Test plan:
make test
=> Adding TypedMetavar for AST generic and AST python (part 1, pfff part)

h_program-lang/ast_generic.ml, lang_GENERIC/parsing/map_ast.ml, lang_GENERIC/parsing/meta_ast.ml, lang_GENERIC/parsing/visitor_ast.ml, lang_c/analyze/c_to_generic.ml, lang_go/analyze/go_to_generic.ml, lang_js/analyze/js_to_generic.ml, lang_ml/analyze/ml_to_generic.ml
This should help fix issue https://github.com/returntocorp/sgrep/issues/65
test plan:
make test still works after the refactoring
=> Merge more field and stmt types. Remove FieldVar and FieldMethod.

h_program-lang/ast_generic.ml, lang_GENERIC/analyze/controlflow_build.ml, lang_GENERIC/parsing/map_ast.ml, lang_GENERIC/parsing/meta_ast.ml, lang_GENERIC/parsing/visitor_ast.ml, lang_go/analyze/go_to_generic.ml, lang_go/parsing/ast_go.ml, lang_go/parsing/meta_ast_go.ml, lang_go/parsing/parse_go.ml, lang_go/parsing/parser_go.mly, lang_go/parsing/parsing_hacks_go.ml, lang_go/parsing/visitor_go.ml, lang_java/parsing/parser_java.mly, tests/go/parsing/case_assign.go, tests/go/parsing/paren_type2.go
Test plan: make test
(the tests are in the sgrep repo)
=> Support '...' in golang in sgrep mode

h_program-lang/ast_generic.ml, lang_python/analyze/python_to_generic.ml
This will help https://github.com/returntocorp/sgrep/issues/201
=> Add Parameter in id_resolved for parameter.

lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/js_to_generic.ml
This should help fix https://github.com/returntocorp/sgrep/issues/195
=> Add resolving information for locals in AST js, so that they propagate to AST generic.

h_program-lang/ast_generic.ml, lang_GENERIC/parsing/map_ast.ml, lang_GENERIC/parsing/meta_ast.ml, lang_GENERIC/parsing/visitor_ast.ml, lang_java/analyze/java_to_generic.ml, lang_js/analyze/js_to_generic.ml, lang_python/analyze/python_to_generic.ml
See https://github.com/returntocorp/sgrep/pull/249
=> import from normalization

h_program-lang/ast_generic.ml, lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/graph_code_js.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/meta_ast_js.ml, lang_js/analyze/visitor_ast_js.ml, lang_js/parsing/cst_js.ml, lang_php/analyze/foundation/ast_php.ml
This will help https://github.com/returntocorp/sgrep/issues/282
Test plan:
~/pfff/pfff_test -dump_ast_js jsx_attr_no_value.js
[V(
{v_name="foo"; v_kind=Const;
v_init=Fun(
{f_props=[]; f_params=[];
f_body=Return((),
Xml(
{xml_tag="main";
xml_attrs=[("attr", String("value"));
("noval", IdSpecial(Null))];
xml_body=[XmlText("
")]; }));
}, None);
v_resolved=Ref(NotResolved); })]
=> Add JSX in AST JS, not just CST JS

h_program-lang/ast_generic.ml, lang_GENERIC/analyze/controlflow.ml, lang_GENERIC/analyze/controlflow_build.ml, lang_GENERIC/analyze/lrvalue.ml, lang_GENERIC/parsing/Makefile, lang_GENERIC/parsing/map_ast.ml, lang_GENERIC/parsing/meta_ast.ml, lang_GENERIC/parsing/visitor_ast.ml
This enables user-defined equivalences in sgrep to
fix issue https://github.com/returntocorp/sgrep/issues/329
Test plan:
make test
=> Add DisjExpr and DisjStmt to AST generic

Makefile, commons_wrappers/Makefile, demos/simple_code_search.ml, h_visualization/Makefile, lang_php/parsing/Makefile, pfff.opam, web/scripts/Makefile
=> remove use of nums.cma which seems unused and is causing issues in CI in opam-repository

graph_code/graph_code.ml, graph_code/graph_code.mli
This is a very small addition to allow easy access to the "has" graph.
=> Added iter_has_edges and all_has_edges to graph_code.

lang_GENERIC/analyze/ast_to_il.ml, lang_GENERIC/analyze/dataflow_tainting.ml, lang_GENERIC/analyze/dataflow_tainting.mli, lang_GENERIC/analyze/il.ml, lang_GENERIC/analyze/ilflow_build.ml, lang_GENERIC/analyze/meta_il.ml, lang_GENERIC/analyze/test_analyze_generic.ml
Hardcoded source/sink/sanitize, but most of the code is there to allow
to parametrize those with semgrep pattern.
=> First version of taint tracking using dataflow

h_program-lang/error_code.ml, h_program-lang/error_code.mli
Relates to https://github.com/returntocorp/semgrep/issues/510
=> h_program-lang/error_code.ml: Add info level

lang_js/parsing/lexer_js.mll, scripts/unicode.ml, tests/js/parsing/unicode_non_breaking_space.js
This closes https://github.com/returntocorp/semgrep/issues/814
Test plan:
=> Support non-breaking space in JS

h_program-lang/AST_generic.ml, lang_GENERIC/analyze/controlflow_build.ml
This will help fix the bug in
https://github.com/returntocorp/semgrep/pull/867
Test plan:
make test
test in semgrep repo
=> Fix vardef_to_assign to also transmit the type info

lang_cpp/parsing/Makefile, lang_go/parsing/Makefile, lang_java/parsing/Makefile, lang_js/parsing/Makefile, lang_ml/parsing/Makefile, lang_python/parsing/Makefile
Modified makefile to echo menhir errors to stdout. Currently also keeps the log, though this is probably not necessary
=> Send menhir errors to stdout

lang_GENERIC/analyze/Unit_typing_generic.ml, tests/GENERIC/typing/FuncParam.go, tests/GENERIC/typing/StaticVarDef.go
Added StaticVarDef.go, which tests for basic variable declarations (given types), and FuncParam.go, which tests for function calls.
Ran with make test
=> Added tests for go typing

Makefile, commons/deprecated/backtrace.ml, graph_code/graph_code.ml, lang_ruby/parsing/utils_ruby.ml, semgrep.yml
=> New semgrep rules!

lang_GENERIC/analyze/Naming_AST.ml, lang_GENERIC/analyze/Unit_typing_generic.ml, tests/GENERIC/typing/ClassFields.java
Modified so that Java class fields are considered EnclosedVar
Tested by writing a sample class with a field
=> Typed class fields for Java

commons/OCaml.ml, commons/OCaml.mli, lang_GENERIC/parsing/Lib_AST.mli, lang_GENERIC/parsing/Visitor_AST.ml, lang_GENERIC/parsing/Visitor_AST.mli, lang_js/analyze/visitor_ast_js.ml, lang_python/parsing/Visitor_python.ml
=> * commons/OCaml.ml: clarify v_ref with v_ref_do_not_visit and v_ref_do_visit

lang_python/analyze/Python_to_generic.ml
test plan:
make test still works
=> * lang_python/analyze/Python_to_generic.ml: this will help Emma unit tests

lang_go/parsing/parser_go.mly, tests/go/parsing/tuples.go, tests/go/parsing/vardecl.go
This will help https://github.com/returntocorp/semgrep/issues/1391
test plan:
+ /home/pad/pfff/pfff -dump_ast tuples.go
[(DirectiveStmt (Package ((), [("foo", ())])));
(DefStmt
({ name = ("foo", ()); attrs = [];
info =
(FuncDef
{ fparams = []; frettype = None;
fbody =
(Block
((),
[(ExprStmt (
(Assign (
(Tuple
[(Id (("a", ()),
{ id_resolved = ref (None);
id_type = ref (None);
));
(Id (("b", ()),
{ id_resolved = ref (None);
id_type = ref (None);
))
]),
(), (Tuple [(L (Int ("1", ()))); (L (Int ("2", ())))])
)),
()));
(ExprStmt (
(AssignOp (
(Tuple
[(Id (("a", ()),
{ id_resolved = ref (None);
id_type = ref (None);
id_const_literal = …
=> Fix wrong order of a,b := 1,2

h_program-lang/AST_generic.ml, lang_GENERIC/parsing/Map_AST.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_GENERIC/parsing/Visitor_AST.ml, lang_go/analyze/go_to_generic.ml, lang_java/analyze/graph_code_java.ml, lang_java/analyze/java_to_generic.ml, lang_java/parsing/ast_java.ml, lang_java/parsing/parser_java.mly, lang_java/parsing/visitor_java.ml, lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/visitor_ast_js.ml, lang_php/analyze/foundation/php_to_generic.ml, lang_python/analyze/Python_to_generic.ml, lang_python/analyze/highlight_python.ml, lang_python/analyze/resolve_python.ml, lang_python/parsing/AST_python.ml, lang_python/parsing/Parser_python.mly, lang_python/parsing/Visitor_python.ml, lang_ruby/analyze/ruby_to_generic.ml
To correctly return range, we need to add in the generic
AST the token for the 'class/interface/trait' keyword.
test plan:
make test
=> Adding token to class_kind in generic AST

lang_python/parsing/Lexer_python.mll, tests/python/parsing/page_break.py, tests/python/parsing/page_break2.py
This fixes https://github.com/returntocorp/semgrep/issues/1501
test plan:
test files included
=> Parsing page break in Python

h_program-lang/AST_generic.ml, lang_GENERIC/analyze/Naming_AST.ml, lang_GENERIC/parsing/Map_AST.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_GENERIC/parsing/Visitor_AST.ml, lang_java/analyze/java_to_generic.ml, lang_java/parsing/ast_java.ml, lang_java/parsing/parser_java.mly, lang_php/analyze/foundation/php_to_generic.ml, lang_python/analyze/Python_to_generic.ml
This will help https://github.com/returntocorp/semgrep/issues/1508
test plan:
See NamedAttr below which now contains ["Foo",();"Bar",()]
instead of a OA_AnnotOther
+ /home/pad/pfff/pfff -dump_ast misc_import_resolve.java
[(DirectiveStmt
(ImportFrom ((), (DottedName [("foo", ())]), ("Bar", ()), None)));
(DefStmt
({ name = ("Foo", ()); attrs = [];
info =
(ClassDef
{ ckind = (Class, ()); cextends = []; cimplements = [];
cmixins = [];
cbody =
((),
[(FieldStmt
(DefStmt
({ name = ("foo", ());
attrs =
[(NamedAttr ((), [("Misc", ())],
id_const_literal = ref (None) },
((), [], ())));
(NamedAttr ((), [("Foo", ()); ("Bar", ())],
{ id_resolved = ref …
=> Generalized AST generic named attribute to have qualified ident

lang_js/analyze/ast_js.ml, lang_js/analyze/transpile_js.mli, lang_js/analyze/visitor_ast_js.ml, lang_js/analyze/visitor_ast_js.mli, tests/js/parsing/jsx/jsx_empty_expr.js
Simple refactoring done while writing Parse_javascript_tree_sitter.ml
test plan:
make
=> Few comments and rename in ast_js.ml

h_program-lang/AST_generic.ml, h_program-lang/meta_ast_generic_common.ml, lang_GENERIC/analyze/AST_to_IL.ml, lang_GENERIC/parsing/Map_AST.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_GENERIC/parsing/Visitor_AST.ml, lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/graph_code_js.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/unit_analyze_js.ml, lang_js/analyze/visitor_ast_js.ml, lang_php/analyze/foundation/abstract_interpreter_php.ml
This will help https://github.com/returntocorp/semgrep/issues/1525
test plan:
make test
=> Extensions to AST generic and ast_js.ml for Parse_javascript_tree_sitter.ml

lang_java/parsing/parser_java.mly, tests/java/semgrep/ellipsis-concat.sgrep
E.g. ... + 3
Fixes returntocorp/semgrep#821
=> Allow ... in Java arithmetic patterns

.circleci/config.yml, Makefile, semgrep.yml
=> New semgrep rule!

.github/workflows/test.yml, Makefile.old, cli/dune, scripts/build, scripts/install, scripts/test
test plan:
dune build
dune runtest -f
=> Remove top Makefile, switch to using dune in CI

ppx/ppx_profiling.ml
If we want to write code using recent OCaml features, e.g. let* monadic
shortcuts, then we can't use PPX extensions using older version of OCaml,
so let's update ppx_profiling to a more recent version of the OCaml AST.
test plan:
make
=> * ppx/ppx_profiling.ml: Update to Ast_08

h_program-lang/Parse_info.ml, h_program-lang/Parse_info.mli, lang_ruby/analyze/il_ruby_build.ml, lang_ruby/analyze/ruby_to_generic.ml, lang_ruby/parsing/ast_ruby.ml, lang_ruby/parsing/parser_ruby.dyp, lang_ruby/parsing/parser_ruby_helpers.ml
Still for https://github.com/returntocorp/semgrep/issues/1609
test plan:
make test
=> * lang_ruby/parsing/ast_ruby.ml: move wrap out of String and into Single

h_program-lang/AST_generic.ml, lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/graph_code_js.ml, lang_js/analyze/highlight_js.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/transpile_js.ml, lang_js/analyze/visitor_ast_js.ml
This is to help at some point matching in semgrep on typescript types.
Test plan:
make
=> Adding type for Typescript type constructions in ast_js.ml

lang_js/analyze/ast_js_build.ml, lang_js/parsing/cst_js.ml, lang_js/parsing/parser_js.mly, lang_js/parsing/visitor_js.ml
should fix issue javascript object ellipsis #1606
=> should fix js object ellipsis parsing

commons_core/parallel.ml
This was very subtle to debug, but when running a command like:
semgrep -l js --timeout 0.5 -e 'FOO' tests/PERF/timeout.js
or even the simpler
/home/pad/github/semgrep/semgrep-core/_build/default/bin/Main.exe -timeout 0.5 -lang js -e FOO tests/PERF/timeout.js -debug -profile
would actually takes 12s to finish! not 0.5s.
Indeed, this is because we currently use Parallel.invoke to run the
tree-sitter parser in its own process (because it segfault or leak memory).
In the case of a short timeout, the timeout is triggered in the
parent process (alarm or timers are not inherited through fork) which
would then finish and close the pipe to the child process. In that case
the child would get an exn that would bubble up and not trigger the exit call,
which would then in Parse_code be captured and …
=> * commons_core/parallel.ml: fix invoke in case of broken pipe

lang_ml/analyze/highlight_ml.ml, lang_ml/parsing/lexer_ml.mll, lang_ml/parsing/parser_ml.mly, lang_ml/parsing/token_helpers_ml.ml, tests/ml/parsing/letop.ml, tests/ml/parsing/letop_use.ml
test plan:
test files included
=> Support for new monadic let in OCaml parser (lang_ocaml/)

.gitignore, commons/file_type.ml, commons/file_type.mli, lang_GENERIC/parsing/Lang.ml, lang_GENERIC/parsing/Lang.mli, lang_GENERIC/parsing/Parse_generic.ml
I didn't think hard about this, just followed my heart and the type checker. Especially the latter.
This is used by the upcoming PR on semgrep.
=> Add TSX as a separate language

lang_GENERIC/analyze/Constant_propagation.ml
So that pattern `foo(1)` will match:
y = 1
x = y + 0
foo(x)
and pattern `foo(True)` will match:
y = True
x = y or False
foo(x)
and pattern `foo("hello world")` will match:
y = "hello"
x = y + " world"
foo(x)
A small step towards returntocorp/semgrep#1645!
=> generic: Perform partial evaluation during constant propagation

lang_c/analyze/c_to_generic.ml, lang_c/analyze/datalog_c.ml, lang_c/analyze/graph_code_c.ml, lang_c/parsing/ast_c.ml, lang_c/parsing/ast_c_build.ml, lang_c/parsing/visitor_c.ml, lang_cpp/analyze/highlight_cpp.ml, lang_cpp/parsing/cst_cpp.ml, lang_cpp/parsing/lexer_cpp.mll, lang_cpp/parsing/parser_cpp.mly, lang_cpp/parsing/parser_cpp2.dyp, lang_cpp/parsing/token_helpers_cpp.ml
This will help https://github.com/returntocorp/semgrep/issues/1694
test plan:
make
test files in semgrep PR
=> Adding <... and ...> to C
