h_program-lang/ast_generic.ml, lang_GENERIC/analyze/lrvalue.ml, lang_GENERIC/parsing/map_ast.ml, lang_GENERIC/parsing/meta_ast.ml, lang_GENERIC/parsing/visitor_ast.ml, lang_js/analyze/js_to_generic.ml, lang_python/analyze/python_to_generic.ml, lang_python/parsing/ast_python.ml, lang_python/parsing/meta_ast_python.ml, lang_python/parsing/parser_python.mly, lang_python/parsing/visitor_python.ml, tests/python/parsing/yield.py
Adds support for the "yield from" construct in Python.
This change uses the same Yield node as a regular Python yield, but sets a boolean indicating that the node represents a yield from.
=> Add support for the "yield from" Python construct

lang_java/CONTRIBUTING.md, lang_java/parsing/test_parsing_java.ml, lang_java/tree_sitter/bblfsh-parser.py, lang_java/tree_sitter/tree-sitter-parser, lang_java/tree_sitter/tree-sitter-parser.js
Added support for invoking Java parse dump from tree-sitter, as well as a CONTRIBUTING.md file that details how to run the parsers from command line.
The following commands are also now available:
```
./pfff -dump_java_new FILENAME.java
./pfff -visitor_java_new FILENAME.java
```
The first allows you to use tree-sitter-java for parsing, and the second prints out tokens as they are parsed.
=> Added Java parsing capability via tree-sitter/babelfish

lang_java/CONTRIBUTING.md, lang_java/parsing/parse_java_with_external_program.ml, lang_java/parsing/test_parsing_java.ml, lang_java/parsing/tree_sitter_ast_java.ml, lang_java/tree_sitter/Toy.java, lang_java/tree_sitter/codegen_grammar.py, lang_java/tree_sitter/codegen_json_parser.py, lang_java/tree_sitter/codegen_node.py, lang_java/tree_sitter/templates.py, lang_java/tree_sitter/toy_new.json
This change addresses many of the comments in [#7](https://github.com/returntocorp/pfff/pull/7), namely creating a file for templates, editing the `Tree_sitter_ast_java` file, and improving naming in the codegen files.
- `codegen-node.py`: After reviewing, tree-sitter `node-type.json` isn't as accurate as `grammar.json`, so `codegen-node.py` is mostly here for posterity (although it does generate pretty good OCaml).
- `codegen_grammar.py`: This is the codegen that we are going to continue working on. The state isn't great right now, a lot of the `tree_sitter_ast_java.ml` file had to be manually edited and there may still need to be diffed against `grammar.json` to make sure it is error-free.
- `codegen_json_parser.py`: I started working on a codegen for JSON parsing, but then went back to …
=> Added documentation for codegen

lang_GENERIC/parsing/find_source.ml, lang_GENERIC/parsing/find_source.mli, lang_GENERIC/parsing/lang.ml
Also support iterating over Java/Go/... in Lang.files_of_...
This should help fix https://github.com/returntocorp/sgrep/issues/66
Test plan:
make test
make install-libs and then in sgrep repo:
./_build/default/bin/main_sgrep.exe -lang javascript -e foo tests/js/
does not raise any exn.
=> Support "javascript" in Find_source for sgrep.

commons/common.ml
Test plan:
make; make reinstall-libs; recompiler sgrep, make install.
create empty dir, sgrep.py --config r2c in it does not raise an exn anymore
=> * commons/common.ml: this should fix https://github.com/returntocorp/sgrep/issues/164

lang_python/analyze/python_to_generic.ml, lang_python/parsing/ast_python.ml, lang_python/parsing/meta_ast_python.ml, lang_python/parsing/parser_python.mly, lang_python/parsing/visitor_python.ml
Test plan:
$ cat misc_import.py
if __name__ == '__main__':
from forget_mult import ForgetMult
else:
from .forget_mult import ForgetMult
$ ~/pfff/pfff_test -dump_generic misc_import.py
Pr(
[If((),
Call(IdSpecial((ArithOp(Eq), ())),
[Arg(
Name(
(("__name__", ()), {name_qualifier=None; name_typeargs=None; }),
{id_resolved=Ref(None); id_type=Ref(None); }));
Arg(L(String(("__main__", ()))))]),
DirectiveStmt(
ImportFrom((), DottedName([("forget_mult", ())]),
[(("ForgetMult", ()), None)])),
DirectiveStmt(
ImportFrom((), FileName(("./forget_mult", ())),
[(("ForgetMult", ()), None)])))])
We now have DottedName vs FileName (before this diff they were
both DottedName and equal.
=> * lang_python/analyze/python_to_generic.ml: This should fix issue https://github.com/returntocorp/sgrep/issues/153

h_program-lang/ast_generic.ml, lang_GENERIC/parsing/map_ast.ml, lang_GENERIC/parsing/meta_ast.ml, lang_GENERIC/parsing/visitor_ast.ml, lang_python/analyze/highlight_python.ml, lang_python/analyze/python_to_generic.ml, lang_python/parsing/ast_python.ml, lang_python/parsing/lexer_python.mll, lang_python/parsing/meta_ast_python.ml, lang_python/parsing/parser_python.mly, lang_python/parsing/token_helpers_python.ml, lang_python/parsing/visitor_python.ml, tests/python/parsing/string_prefix.py
This should help fix https://github.com/returntocorp/sgrep/issues/157
Test plan:
$ cat string_prefix.py
foo = b"a str"
$ ~/pfff/pfff -dump_python string_prefix.py
[Assign([Name(("foo", ()), Store, Ref(NotResolved))], (),
EncodedStr(("a str", ()), "b"))]
=> * h_program-lang/ast_generic.ml: add support for EncodedString as in Python and fix Python lexer to record this information.

lang_go/analyze/go_to_generic.ml, lang_python/analyze/python_to_generic.ml
This is related to https://github.com/returntocorp/sgrep/pull/193/files
Test plan:
BEFORE
+ /home/pad/github/sgrep/_build/default/bin/main_sgrep.exe -lang go -dump_pattern dots_stmts2.sgrep
Ss(
[Block(
[DefStmt(
({name=("$SOME", ()); attrs=[KeywordAttr((Var, ()))]; tparams=[
]; info={id_resolved=Ref(None); id_type=Ref(None); }; },
VarDef({vinit=Some(L(String(("...", ())))); vtype=None; })))]);
ExprStmt(Ellipsis(()));
Block(
[DefStmt(
({name=("$OTHER", ()); attrs=[KeywordAttr((Var, ()))]; tparams=[
]; info={id_resolved=Ref(None); id_type=Ref(None); }; },
VarDef(
{
vinit=Some(Name(
(("$Z", ()),
{name_qualifier=None; name_typeargs=None; }),
{id_resolved=Ref(None); id_type=Ref(None); }));
vtype=None; })))])])
bugfix/go-stmts/home/pad/github/sgrep/tests/go $
AFTER
+ …
=> Remove extra Block around vars, especially for sgrep patterns.

lang_java/analyze/graph_code_java.ml, lang_java/analyze/highlight_java.ml, lang_java/analyze/java_to_generic.ml, lang_java/parsing/ast_java.ml, lang_java/parsing/meta_ast_java.ml, lang_java/parsing/parse_java.ml, lang_java/parsing/parser_java.mly, lang_java/parsing/visitor_java.ml
As titled. Adds Ellipsis as a decl, so that it could 
used inside class, enum, interface body.
1. make test
2. Cross compile to sgrep and run `dune runtest` there. See https://github.com/returntocorp/sgrep/pull/259
```
ulziibayarotgonbaatar@ulziibayars-MacBook-Pro sgrep % ./_build/default/bin/main_sgrep.exe -dump_pattern tests/java/less_inheritance.sgrep -lang java                       
S(
DefStmt(
({name=("A", ()); attrs=[]; tparams=[]; 
info={id_resolved=Ref(None); id_type=Ref(None); 
},
ClassDef(
{ckind=Class; cextends=[]; cimplements=[]; cmixins=[]; 
cbody=[FieldStmt(ExprStmt(Ellipsis(())))]; }))))
```
=> Java Class Ellipsis in body

lang_GENERIC/parsing/lang.ml, lang_GENERIC/parsing/lang.mli
Used to print
```
Language ext to language mappings:
c->c
go->go
golang->go
java->java
javascript->js
js->js
ml->mli, ml, mly, mll
ocaml->mli, ml, mly, mll
py->py, pyi
python->py, pyi
```
in sgrep. Addresses: https://github.com/returntocorp/sgrep/issues/246
=> Add ext of language

lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/meta_ast_js.ml, lang_js/analyze/visitor_ast_js.ml, lang_js/parsing/cst_js.ml, lang_js/parsing/meta_cst_js.ml, lang_js/parsing/parser_js.mly, lang_js/parsing/visitor_js.ml
This turned out to require some refactoring where we used to
just return a list of stmts, then a list of items,
and now we need to return a list of toplevel elements (module_items).
An alternative used by Ulzii was to add a new ImportDecl in the CST
and AST at the stmt level (or item level), but I prefer to have the
CST and AST enforce as much language restrictions as possible (Javascript
allows ES6 import declaration just at the toplevel!)
This should help fix https://github.com/returntocorp/sgrep/issues/250
Test plan:
make test work
relevant tests added in sgrep repo instead
=> Allow import declaration in JS sgrep pattern

lang_go/parsing/parser_go.mly, tests/go/parsing/misc_empty.go
This should fix issue https://github.com/returntocorp/sgrep/issues/281
Test plan:
$ ~/pfff/pfff -dump_go ~/pfff/tests/go/parsing/misc_empty.go
{package=((), ("Foo", ())); imports=[];
decls=[DFunc(("bar1", ()),
({fparams=[]; fresults=[]; },
Block([SimpleStmt(ExprStmt(Call((Id(("bar", ())), []))))])));
DFunc(("bar2", ()),
({fparams=[]; fresults=[]; },
Block([SimpleStmt(ExprStmt(Call((Id(("bar", ())), []))))])));
DFunc(("bar3", ()),
({fparams=[]; fresults=[]; },
Block([SimpleStmt(ExprStmt(Call((Id(("bar", ())), []))))])))];
}
No more Empty at the end of the Block
=> Remove hidden Empty originally added by the Go Parser

lang_js/parsing/parse_js.ml
Some arrows using parenthesis, as in (a) => { ... } require
some parsing hacks to convert the open parenthesis in a special token.
I was not performing this hack for the sgrep pattern, which prevented
to parse certain arrows in a sgrep pattern.
This should help fix https://github.com/returntocorp/sgrep/issues/267
Test plan:
test files for sgrep included.
=> Use parsing JS hacks also for the sgrep pattern, fix arrow parsing

lang_js/parsing/lexer_js.mll
This should help https://github.com/returntocorp/sgrep/issues/282
Test plan:
develop/home/pad/github/sgrep/sgrep/tests/js $ pwd
/home/pad/github/sgrep/sgrep/tests/js
develop/home/pad/github/sgrep/sgrep/tests/js $ ~/pfff/pfff -lang js -dump_pattern less_xml_attr.sgrep
E(
Xml(
{xml_tag=("div", ());
xml_attrs=[(("dangerouslySetInnerHTML", ()), L(String(("...", ()))))];
xml_body=[]; }))
=> Allow JSX as first element in a file in sgrep mode.

lang_GENERIC/analyze/naming_ast.ml, lang_GENERIC/parsing/parse_generic.ml, lang_go/analyze/resolve_go.ml, lang_js/analyze/js_to_generic.ml, lang_python/analyze/resolve_python.ml
This should fix issue https://github.com/returntocorp/sgrep/issues/260
by side effect
test plan:
make test in sgrep still work
=> lang_GENERIC/analyze/naming_ast.ml: port Go and Python aliasing to generic naming. Disable the pl-specific resolvers in parse_generic!

lang_c/parsing/ast_c_build.ml, lang_c/parsing/test_parsing_c.ml, lang_cpp/parsing/cst_cpp.ml, lang_cpp/parsing/flag_parsing_cpp.ml, lang_cpp/parsing/meta_cst_cpp.ml, lang_cpp/parsing/parser_cpp.mly, lang_cpp/parsing/parser_cpp2.dyp, lang_cpp/parsing/parser_cpp_mly_helper.ml, tests/c/parsing_errors/error_recovery.c
This can help a bit fix issue https://github.com/returntocorp/sgrep/issues/448
Test plan:
~/pfff/pfff -macros pfff_macros.h  -parse_c git/remote-curl.c
does not throw List.hd exn anymore (but throw no ifdef issue)
=> Do not use token list for int and float type, fix List.hd exn

lang_java/parsing/parser_java.mly
Test plan:
~/pfff/pfff -lang java -dump_pattern dots_attribute.sgrep
S(
DefStmt(
({name=("$METHOD", ());
attrs=[NamedAttr(("RequestMapping", ()),
{id_resolved=Ref(None); id_type=Ref(None);
id_const_literal=Ref(None); }, [Arg(Ellipsis(()))]);
KeywordAttr((Public, ()))];
tparams=[];
info={id_resolved=Ref(None); id_type=Ref(None);
},
FuncDef(
{fparams=[ParamEllipsis(())];
frettype=Some(TyName(
(("$T", ()),
{name_qualifier=Some([]); name_typeargs=None; })));
fbody=Block([ExprStmt(Ellipsis(()))]); }))))
=> * lang_java/parsing/parser_java.mly: Add support for '...' in annotations

lang_js/analyze/ast_js.ml, lang_js/analyze/js_to_generic.ml, lang_js/parsing/cst_js.ml, tests/js/parsing/void0.js
This closes https://github.com/returntocorp/sgrep/issues/492
Test plan:
~/pfff/pfff -dump_ast void0.js
Pr(
[DefStmt(
({name=("foo", ()); attrs=[KeywordAttr((Const, ()))]; tparams=[];
info={id_resolved=Ref(None); id_type=Ref(None);
},
FuncDef(
{fparams=[]; frettype=None;
fbody=If((),
Call(IdSpecial((ArithOp(PhysEq), ())),
[Arg(
Id(("x", ()),
{id_resolved=Ref(None); id_type=Ref(None);
id_const_literal=Ref(None); }));
Arg(Cast(TyBuiltin(("void", ())), L(Float(("0", ())))))]),
Return((), Some(L(Undefined(())))), Block([]));
})))])
=> * tests/js/parsing/void0.js: support!

lang_python/parsing/lexer_python.mll, tests/python/parsing/nonlocal.py
Oops ...
This should fix https://github.com/returntocorp/semgrep/issues/555
The python parser does switch to python2 mode when there is a parse
error in Python3 mode, so one could think that even with my typo
this should have worked, but it does so using an heuristic that looks
whether a python3 keyword was used, and this nonlocal was an
ID in python3 mode (the bug), and so it did not even try to go in python2 mode.
Test plan:
=> * tests/python/parsing/nonlocal.py: Support

lang_python/parsing/parser_python.mly, tests/python/parsing/format1.py
This should fix https://github.com/returntocorp/semgrep/issues/535
Test plan:
=> * tests/python/parsing/format1.py: support

lang_python/parsing/lexer_python.mll
pfff would fail to parse python code ending with a comment.
For example:
if 2 == 2:
print('hello')
#
Where the last line does not end with a newline.
Extend the eof pattern of the _token rule of the python lexer to
resolve this. The missing newline is already handled by a python parsing
hacks fix.
This is a fix for the issue returntocorp/semgrep#240.
Signed-off-by: Jaskaran Singh <jaskaransingh7654321@gmail.com>
=> * lang_python/parsing/lexer_python.mll: File ending comment fix

lang_python/parsing/parser_python.mly, tests/python/parsing/format1.py
Previously, f-strings were failing to parse format syntax with `%` symbol in it.
This commit adds that behavior and includes tests.
=> Parse % in fstring format

lang_python/parsing/parser_python.mly, tests/python/parsing/fstrings.py
Previously, f-strings could only accept expressions that could also
appear as Python statements. However, Python automatically converts
comma-separated lists in f-string interpolants into tuples.
This commit adds that behavior to pfff's Python parser as well.
This was trio-programmed with @brendongo and @minusworld
=> Correctly parse tuples inside Python f-strings

lang_java/parsing/lexer_java.mll, tests/java/semgrep/escape_char.sgrep
This fixes https://github.com/returntocorp/semgrep/issues/743
Test plan:
+ /home/pad/pfff/pfff -lang java -dump_pattern escape_char.sgrep
E(
Call(
DotAccess(
Id(("$SE", ()),
{id_resolved=Ref(None); id_type=Ref(None);
id_const_literal=Ref(None); }), (), FId(("eval", ()))),
[Arg(L(String(("=~/.*dev\.corp\.com.*/", ()))))]))
not anymore a parse error :)
=> Support more excaped sequences for Java in semgrep parsing mode

lang_java/parsing/parser_java.mly
Addresses https://github.com/returntocorp/semgrep/issues/723.
Tested it against
String sb = "a";
String a;
as described in the issue. Made test.java with that pattern and ran
./pfff -dump_pattern test.java -lang java
=> Parse list of statements in pattern for Java

lang_GENERIC/analyze/Normalize_AST.ml, lang_GENERIC/analyze/Normalize_AST.mli
In some instances, Python != is not the same as (not ... == ...), as
Python will call `__ne__(...)` on objects.
To deal with this, we skip AST normalization for != nodes in Python.
=> Exclude Python from normalization

lang_cpp/parsing/Makefile, lang_go/parsing/Makefile, lang_java/parsing/Makefile, lang_js/parsing/Makefile, lang_ml/parsing/Makefile, lang_python/parsing/Makefile, scripts/check_menhir_conflicts.sh, scripts/check_ocamlyacc_conflicts.sh
Addresses: https://github.com/returntocorp/semgrep/issues/800#event-3356766862
Test plan:
For each language implemented (js, ml, cpp, java, python, go), set the number of permitted conflicts to one below the actual number of conflicts. Run make clean then make twice (either top level or in the test_[lang]/parsing folder). In at least one case when there are no conflicts: introduce a conflict deliberately.
Note: the menhir version has been tested with one conflict, 2 conflicts, >100 conflicts, just shift/reduce, just reduce/reduce, and both shift/reduce and reduce/reduce. The ocamlyacc version has only been tested with the case "1 shift/reduce conflict".
=> Add checks so that number of grammar conflicts can't increase without notice

h_program-lang/AST_generic.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/meta_ast_js.ml, lang_js/analyze/visitor_ast_js.ml, lang_js/parsing/cst_js.ml, lang_js/parsing/meta_cst_js.ml, lang_js/parsing/parser_js.mly, lang_js/parsing/visitor_js.ml, tests/js/parsing/backquote.js, tests/js/parsing/template_string.js, tests/js/parsing/template_string_member.js, tests/js/parsing/template_string_react.js, tests/js/parsing/template_string_tag.js
This fixes https://github.com/returntocorp/semgrep/issues/823
Test plan:
test files included, they now parse correctly without any parse error
exceptions and their AST dump looks ok.
=> Support for template strings used as argument to member expression

lang_go/parsing/parsing_hacks_go.ml, tests/go/parsing/if_header_lbody2.go
The Go grammar is not LALR(1). To manage some ambiguity we need
to use some parsing hack to find the opening brace of an if/for/switch/select.
This add a new heuristic to not treat the { of interface as the
opening brace.
This fixes https://github.com/returntocorp/semgrep/issues/829
Test plan:
=> Support use of interface{} inside if/for/..., parsing hack

lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/graph_code_js.ml, lang_js/analyze/graph_code_js.mli, lang_js/analyze/highlight_js.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/meta_ast_js.ml, lang_js/analyze/transpile_js.ml, lang_js/analyze/visitor_ast_js.ml
As said in ast_js.ml, having Nop in the AST simplified a few things
but hurt us in Semgrep so I've removed it.
This fixes https://github.com/returntocorp/semgrep/issues/824
Test plan:
There is more a vinit = Some Nop below, but instead a None
I'll add a regression test in semgrep-core in another PR.
+ /home/pad/pfff/pfff -dump_ast misc_notoken.js
Pr(
[DefStmt(
({name=("bar", ());
attrs=[KeywordAttr((Const, ())); KeywordAttr((Async, ()))];
tparams=[];
info={id_resolved=Ref(None); id_type=Ref(None);
},
FuncDef(
{
fparams=[ParamClassic(
{pname=Some(("msg", ())); pdefault=None; ptype=None;
pattrs=[];
pinfo={id_resolved=Ref(None); id_type=Ref(None);
})];
frettype=None;
fbody=Block(
[DefStmt(
({name=("x", ()); …
=> Remove Nop from the Javascript AST to remove some NoTokenLocation exception

.gitignore, lang_python/analyze/Python_to_generic.ml, lang_python/analyze/highlight_python.ml, lang_python/parsing/AST_python.ml, lang_python/parsing/Lexer_python.mll, lang_python/parsing/Meta_AST_python.ml, lang_python/parsing/Parser_python.mly, lang_python/parsing/Token_helpers_python.ml, lang_python/parsing/Visitor_python.ml, tests/python/parsing/python3/walrus-invalid.py, tests/python/parsing/python3/walrus.py
Python introduced support for expression-level assignment in 3.8 via the
"Walrus" operator, ":=". Add that to Python parsing here.
Note that Python's grammar handles assignment expressions within
arguments separately from "test" expressions; that difference is
included here verbatim from
https://docs.python.org/3/reference/grammar.html.
In both those cases I condense the Python AST to the same "Assign" node
in the generic AST (although arguments are nested within an "Arg" node
as well).
Test cases are taken directly from PEP 572:
https://www.python.org/dev/peps/pep-0572/.
Bonus:
Ignore menhir-out.log files.
=> Add support for Python's Walrus (:=) operator

lang_python/parsing/Parser_python.mly, tests/python/parsing/python2/print.py
Previously, we only parsed:
print
print x
print x, y
print x, y,
and print statements with longer argument lists. However,
print x,
is also valid python2. Support that.
=> Properly parse print with dangling comma in python 2

lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/graph_code_js.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/meta_ast_js.ml, lang_js/analyze/visitor_ast_js.ml, lang_js/parsing/cst_js.ml, lang_js/parsing/meta_cst_js.ml, lang_js/parsing/parser_js.mly, lang_js/parsing/visitor_js.ml, tests/js/parsing/try-catch.js
In ES2019+, the value binding after the `catch` keyword is optional.
Support that here, and add a test case.
=> Add support for optional catch bindings in ECMAScript 2019

lang_js/parsing/cst_js.ml, lang_js/parsing/meta_cst_js.ml, lang_js/parsing/parser_js.mly, lang_js/parsing/visitor_js.ml, tests/js/parsing/async.js
Unfortunately this means manually resolving shift-reduce conflicts by
enumerating grammar possibilities for async arrow functions.
Also added a test case to validate.
Fixes https://github.com/returntocorp/semgrep/issues/562.
=> Support `() => async () => {}` syntax for ECMAScript

.circleci/config.yml, Dockerfile, scripts/build, scripts/install, scripts/install-opam-deps, scripts/setup-debian, scripts/test
* I added a simple Dockerfile to serve as a model on how to build the project (addresses #114). The little quirks are buried in scripts `./scripts/build` etc.
* The CircleCI config now uses the new scripts. It works.
* ~~The GitHub Actions config also uses the new scripts. I don't know if it works.~~
~~It would be good to test the new GH-Actions config before merging into master. I don't know if it's possible. Note that it's also going to be slower than CircleCI because it rebuilds all the opam base each time. Or maybe there's an easy way to specify a custom base docker image like we do with CircleCI? I would like to say that the GitHub Actions documentation pales in comparison to CircleCI.~~
Update: I gave up on fixing things for GitHub Actions. I can't make something clean for this. The …
=> Share build scripts among Dockerfile/CircleCI/GH-Actions

lang_js/analyze/transpile_js.ml, tests/js/parsing/spread_params.js
Here we transpile:
```js
var {...a} = b;
```
into
```js
var a = <spread>(b);
```
This is a bit of a hack, as really the rest param here is equivalent to
ommitting unselected keys. However, there's no built-in within
ECMAScript to perform this omission beyond the object rest param.
Note that this will cause us to confuse the rest parameter in these two
cases:
var {...a} = b;
var {x, ...a} = b;
I'm leaving this as an existing wart for now.
The "spread_params.js" test case is updated (although this is a "rest",
rather than a "spread" parameter, with inverse functionality).
Fixes returntocorp/semgrep#581
=> Parse rest param in object destructuring

lang_java/parsing/parser_java.mly, tests/java/parsing/NewArrayAccess.java, tests/java/parsing/NewArrayMultidim.java
Fixes https://github.com/returntocorp/semgrep/issues/906
My understanding is that this construct falls outside of the official grammar specification, but it is implemented in javac and we have to support it.
=> Java parsing: Allow access to new array with an initializer.

lang_python/parsing/Parser_python.mly, tests/python/parsing/python2/raise.py
In Python2, exceptions can be named with either a comma or an "as",
whereas in Python3 only "as" is allowed.
This commit extends pfff to recognize the comma Python2 syntax.
For information on the Python 2 grammar, see:
https://docs.python.org/2/reference/grammar.html
For information on the Python 3 grammar, see:
https://docs.python.org/3/reference/grammar.html
Fixes https://github.com/returntocorp/semgrep/issues/926
=> Properly parse python2 "except Exception, ex:" handler

lang_python/parsing/Lexer_python.mll, lang_python/parsing/Parse_python.ml, tests/python/parsing/fstrings.py
Fixes returntocorp/semgrep#945.
=> python: Parse triple-single-quoted f-strings f'''…'''

lang_js/analyze/js_to_generic.ml
This is meant to fix https://github.com/returntocorp/semgrep/issues/443
I'm not sure about my approach (see TODO comments). Perhaps changing the matcher in semgrep would be preferable? Or maybe a change in the structure of the generic tree?
=> WIP: Ensure that javascript function bodies are all blocks.

lang_GENERIC/analyze/Makefile, lang_GENERIC/analyze/Naming_AST.ml, lang_GENERIC/analyze/Unit_naming_generic.ml, lang_GENERIC/analyze/Unit_naming_generic.mli, main_test.ml, tests/python/naming/shadow_name_type.py
This should fix https://github.com/returntocorp/semgrep/issues/923
The issue was that we now annotate certain expression Id with their type,
but in some languages such as Python where there is no clean types,
they use expressions to represent type and those type can then contain
Id that will get associate a type and create cycle in the generic AST,
which then lead certain code (e.g., dumper) to loop forever.
test plan:
regression tests included
make test
~/pfff/pfff -naming_generic shadow_...py does not loop forever anymore
=> Fix infinite loop in AST_generic naming phase

lang_GENERIC/analyze/Naming_AST.ml
This is related to https://github.com/returntocorp/semgrep/issues/923
In my previous fix I've disabled the recursion on OtherType to avoid
creating cycles in the AST but doing so I've introduced some regressions
in semgrep (in tests/python/misc_regression1.py) because we were not
resolving correctly aliases anymore.
This fixes the fix.
Test plan:
+ /home/pad/pfff/pfff -dump_ast -naming_generic python/misc_regression1.py
now shows the right id_resolved
and we still do not go into infinite loop
=> Fix regression in semgrep on disabling naming of OT_Expr

h_program-lang/AST_generic.ml, lang_GENERIC/parsing/Map_AST.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_GENERIC/parsing/Visitor_AST.ml, lang_js/analyze/js_to_generic.ml, lang_ml/analyze/ml_to_generic.ml, tests/js/parsing/class_field_vs_method.js
This should help fix https://github.com/returntocorp/semgrep/issues/941
In semgrep we don't want var definition
(or assignment, which are matched against var definition) to match
field definitions.
This slightly reverts 4df9110328bcccd27eaafc72acf0038f1272f691
but use a FieldDef instead of a FieldVar which helps keep
the code in semgrep short.
Test plan:
=> Separate var definition from field definition

lang_ruby/analyze/dQueue.ml, lang_ruby/parsing/ast_ruby_helpers.ml, lang_ruby/parsing/utils_ruby.ml
This does not work anymore in 4.10.0
and we don't care about ocaml < 4.07
test plan:
git grep Pervasives.
but we should really use semgrep for ocaml in CI to prevent those!
especially since the one remaining are in comments :)
=> Remove use of Pervasives

.github/workflows/test.yml, Makefile, external/ppx_deriving, lang_ml/analyze/Makefile, lang_ml/analyze/ast_ml.ml, lang_ml/analyze/test_analyze_ml.ml, lang_ml/parsing/Makefile, lang_ml/parsing/cst_ml.ml, lang_ml/parsing/parser_ml.mly, lang_ml/parsing/test_parsing_ml.ml, pfff.opam, scripts/install-opam-deps, tests/ml/parsing/attributes.ml
Ppx_deriving is a better option than my ocamltarzan for
the different AST dumpers in Pfff. They are automatically generated
and up-to-date as opposed to ocamltarzan meta_ast_xxx.ml which
are first auto-generated but then need to be modified manually
for each modification on the original AST
test plan:
make
the output of -dump_ml (ocamltarzan based) and -show_ml is mostly
the same.
~/pfff/pfff -show_ml foo.ml
(Program
[(TopItem
(Let ((), None,
[(Left
(LetClassic
{ l_name = (Name ("x", ()));
l_params =
[(ParamPat (PatVar (Name ("a", ()))));
(ParamPat (PatVar (Name ("b", ()))))];
l_tok = ();
l_body =
[(Left
(FunCallSimple (
([((Name ("Pervasives", ())), ())],
(Name ("compare", ()))),
[(ArgExpr (L ([], (Name ("a", ())))));
(ArgExpr (L ([], (Name ("b", ())))))]
)))
]
}))
]
)))
]) …
=> Start using ppx_deriving and introduce new -show_ml action

lang_java/parsing/parser_java.mly
This feature now works due to https://github.com/returntocorp/semgrep/pull/987/files
=> Removed guard against metavariable types

.github/workflows/test.yml, Makefile, demos/Makefile, external/uucp, external/uutf, h_program-lang/Makefile, h_program-lang/Parse_info.ml, h_program-lang/Parse_info.mli, h_program-lang/Unicode.ml, h_program-lang/Unicode.mli, lang_go/parsing/parse_go.ml, lang_java/parsing/lexer_java.mll, lang_java/parsing/parse_java.ml, lang_js/parsing/lexer_js.mll, lang_js/parsing/parse_js.ml, lang_php/pretty/Makefile, lang_python/parsing/Parse_python.ml, lang_python/parsing/Test_parsing_python.ml, pfff.opam, scripts/install-opam-deps, tests/java/parsing/Unicode.java, tests/python/parsing/unicode.py
As a preprocessing step before parsing, this attempts to replace characters outside the ascii range by ascii characters. If the unicode character "whitespace", it gets replaced by spaces, otherwise it gets replaced by Zs. The length of the replacement string should be equal to the original UTF-8 sequence being replaced in most cases (but it's not guaranteed due to Unicode having multiple ways of encoding the same character. See https://www.wikiwand.com/en/Unicode_equivalence#/Normalization).
=> Replace non-ascii UTF-8 characters by Zs or spaces

lang_GENERIC/analyze/Naming_AST.ml, lang_GENERIC/analyze/Unit_typing_generic.ml, tests/GENERIC/typing/PropVarDef.go
Propagated literal types, attempted to propagate id types as well but currently still always None
Tested against below by manually checking the results
package main
func main() {
var a = 3
var b = "hello"
var d = a
}
=> Modified to propagate literal types

lang_json/parsing/parse_json.ml
test plan:
~/pfff/pfff -lang json -dump_pattern metavar_array.json
now works
=> * lang_json/parsing/parse_json.ml: correctly parse JSON semgrep pattern

lang_js/analyze/highlight_js.ml, lang_js/parsing/cst_js.ml, lang_js/parsing/lexer_js.mll, lang_js/parsing/parser_js.mly, lang_js/parsing/parsing_hacks_js.ml, lang_js/parsing/token_helpers_js.ml, tests/js/parsing/react_fragment.js, tests/js/parsing/react_short_fragment.js
This fixes https://github.com/returntocorp/semgrep/issues/435
and https://github.com/returntocorp/semgrep/issues/782
Test plan:
~/pfff/pfff -sgrep_mode -lang js -dump_pattern misc_object_directly.sgrep
(E
(Record
((),
[(FieldStmt
(DefStmt
({ name = ("fld1", ()); attrs = [];
info =
(FieldDef
{ vinit =
(Some (Id (("$X", ()),
{ id_resolved = ref (None);
id_type = ref (None);
)));
vtype = None }))))
],
())))
=> Support {} semgrep pattern in JS directly

lang_js/parsing/lexer_js.mll, tests/js/parsing/arrow.js, tests/js/parsing/ext_decorators_at.js, tests/js/parsing/react_short_fragment2.js, tests/js/parsing/react_short_fragment3.js
This closes https://github.com/returntocorp/semgrep/issues/1009
There is actually a real error in this file.
Test plan:
Test file included
~/pfff/pfff -dump_ast react_short_fragment3.js
shows a good dump, not anymore a parse error
=> Test file showing we now support <> and complex JS

lang_GENERIC/analyze/Naming_AST.ml, tests/java/parsing/AnnotVar.java, tests/php/semantic/global.php, tests/python/semantic/global.py
This will help https://github.com/returntocorp/semgrep/issues/1101
Test plan:
The dump below now show Global, 1 also for reference.
~/pfff/pfff -naming_generic global.py
(Pr
[(ExprStmt (
(Assign (
(Id (("GLOBAL", ()),
{ id_resolved = ref ((Some (Global, 1))); id_type = ref (None);
)),
(), (L (Int ("1", ()))))),
()));
(DefStmt
({ name = ("foo", ()); attrs = [];
info =
(FuncDef
{ fparams = []; frettype = None;
fbody =
(Block
((),
[(ExprStmt (
(Call (
(Id (("print", ()),
)),
((),
[(Arg
(Id (("GLOBAL", ()),
{ id_resolved = ref ((Some (Global, 1)));
id_type = ref (None); …
=> * lang_GENERIC/analyze/Naming_AST.ml: Fix lookup semantic of Python

lang_GENERIC/analyze/Constant_propagation.ml, lang_GENERIC/analyze/Constant_propagation.mli, lang_GENERIC/analyze/Makefile, lang_GENERIC/analyze/Naming_AST.ml
This will help improve the constant propagation heuristic.
Right now it's too tangled with naming, which prevents me to add
some simple heuristics like propagation for the 'final' Java keyword.
Test plan:
make test
and make test in semgrep-core after a make reinstall-libs
=> Move out constant propagation out of naming in its own file

h_program-lang/AST_generic.ml, lang_GENERIC/analyze/Constant_propagation.ml, lang_GENERIC/analyze/Test_analyze_generic.ml, tests/java/naming/unknown_var.java
This will help https://github.com/returntocorp/semgrep/issues/1088
Test plan:
see id_const_literal below
~/pfff/pfff -constant_propagation equivalence_constant_propagation.java
(Pr
[(DefStmt
({ name = ("SemgrepTest", ()); attrs = [(KeywordAttr (Public, ()))];
info =
(ClassDef
{ ckind = Class; cextends = []; cimplements = []; cmixins = [];
cbody =
((),
[(FieldStmt
(DefStmt
({ name = ("MD5_1", ());
attrs =
[(KeywordAttr (Public, ()));
(KeywordAttr (Static, ()));
(KeywordAttr (Final, ()))];
info =
{ id_resolved = ref ((Some (EnclosedVar, 1)));
id_type =
ref ((Some (TyName
(("String", ()),
{ name_qualifier = (Some []);
name_typeargs = None }))));
id_const_literal =
ref ((Some (String ("MD5", …
=> Support 'final' for const propagation

lang_GENERIC/analyze/Constant_propagation.ml, lang_GENERIC/analyze/Constant_propagation.mli
This partially solves https://github.com/returntocorp/semgrep/issues/349
Test plan:
test file in semgrep_core.
See id_const_literal for CONST_GLOBAL below!
~/pfff/pfff -constant_propagation equivalence_constant_propagation.py
(Pr
[(ExprStmt (
(Assign (
(Id (("CONST_GLOBAL", ()),
{ id_resolved = ref ((Some (Global, 1))); id_type = ref (None);
id_const_literal = ref ((Some (String ("secret", ())))) }
)),
(), (L (String ("secret", ()))))),
()));
(ExprStmt (
(Assign (
(Id (("GLOBAL", ()),
{ id_resolved = ref ((Some (Global, 2))); id_type = ref (None);
)),
(), (L (String ("secret", ()))))),
()));
(DefStmt
=> Basic const analysis for Python for basic const propagation for semgrep

h_program-lang/AST_generic.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_python/analyze/Python_to_generic.ml, lang_python/parsing/AST_python.ml, lang_python/parsing/Parser_python.mly, lang_python/parsing/Visitor_python.ml, tests/python/parsing/python2/raise.py, tests/python/parsing/python2/raise.sgrep
This is a one-off construct in python2, so I add a one-off node in the
generic AST: OS_ThrowArgsLocation to handle it. Doing so will allow us
to match all these expressions.
Fixes returntocorp/semgrep#1162.
=> Parse python2 "raise expr, expr, expr"

lang_python/parsing/Parser_python.mly, tests/python/parsing/trailing.py
For whatever reason, the Python interpreter allows you to leave dangling
whitespace after the last statement in a Python file, and this does not
actually get interpreted as indentation.
I couldn't figure out exactly what the lexer was doing here, but it
parses trailing whitespace (all on one line) as:
INDENT NEWLINE DEDENT NEWLINE EOF
Here I just match against this magic code and drop it at the end of
a file.
Fixes returntocorp/semgrep#312.
=> Parse trailing whitespace in Python files

lang_python/analyze/Python_to_generic.ml, lang_python/analyze/highlight_python.ml, lang_python/analyze/resolve_python.ml, lang_python/parsing/AST_python.ml, lang_python/parsing/Parser_python.mly, lang_python/parsing/Visitor_python.ml, tests/python/parsing/python2/pattern.py, tests/python/parsing_errors/python2/pattern.py
Adds the ability to parse
```
def foo((x, y)):
...
```
and
```
lambda (x, y): ...
```
Note that the solution here would allow funky mixed Python2/3 syntax:
```
def foo(x: int, (y, z)):
...
```
But this should be ok for code search.
Fixes returntocorp/semgrep#994.
Fixes returntocorp/semgrep#1164.
=> Parse Python2 tuple patterns

h_program-lang/AST_generic.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_python/analyze/Python_to_generic.ml, lang_python/analyze/highlight_python.ml, lang_python/analyze/resolve_python.ml, lang_python/parsing/AST_python.ml, lang_python/parsing/Parser_python.mly, lang_python/parsing/Visitor_python.ml, tests/python/parsing/params-positional-only.py
PEP 570 adds a single slash as a demarcation between positional-only and
classic Python 3 parameters. This commit adds parsing support.
Fixes returntocorp/semgrep#1165.
=> Parse Python 3.8 positional-only demarcator

.circleci/config.yml, lang_python/parsing/Parser_python.mly
In bc9cdad83, we resolved a S/R conflict by choosing to represent
"expression" type Python sgrep patterns as ExprStmt nodes. This appears
to have caused regressions within semgrep. Let's instead resolve by
choosing to represent these patterns as Expr nodes.
I validated that this works in semgrep/semgrep-core by:
opam uninstall pfff
opam install ../pfff
make clean
make
make install
make test
=> Return python Expr for sgrep expressions

lang_python/parsing/Lexer_python.mll, lang_python/parsing/Parse_python.ml, tests/python/parsing/python2/reassign-true.py
In Python 2 they are names, not keywords.
Fixes returntocorp/semgrep#1168.
=> Parse Python 2 "True" and "False" as names

lang_js/analyze/transpile_js.ml, tests/js/parsing/pattern_nested.js, tests/js/parsing/pattern_param.js
Previously, our transpilation step (necessary for creating a generic
AST) for JavaScript could not handle nested array patterns.
Note that JavaScript does not support nested object patterns (instead,
one would assign to the right-hand-side of a property pattern), so we
fail hard in this case.
After this commit, patterns like:
```javascript
function foo([a, [b, {c}]]) { ... }
```
Will be transpiled to:
```javascript
function foo(arg0) {
let a = arg0[0];
let b = arg0[1][0];
let c = arg0[1][1].c;
}
```
Fixes returntocorp/semgrep#582
=> Create generic AST from nested JS patterns

lang_js/analyze/ast_js.ml, lang_js/analyze/ast_js_build.ml, lang_js/analyze/graph_code_js.ml, lang_js/analyze/js_to_generic.ml, lang_js/analyze/map_ast_js.ml, lang_js/analyze/visitor_ast_js.ml, lang_js/parsing/cst_js.ml, lang_js/parsing/parser_js.mly, lang_js/parsing/visitor_js.ml, tests/js/parsing/pattern_catch.js
ECMA 2021 allows for binding parameters in the argument to catch
expressions. See https://tc39.es/ecma262/#prod-CatchParameter.
This commit adds support for them.
Fixes returntocorp/semgrep#1040.
=> Support binding patterns in JS catch-expressions

h_program-lang/AST_generic.ml, lang_GENERIC/parsing/Map_AST.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_GENERIC/parsing/Visitor_AST.ml
Added node Modn to AST in order to correctly call envf. DId this in order to fix the go metavariable parsing error issue 638.
=> Go Metavariable Parsing Bug Fix

pfff.opam
This avoids a problem in my environment, where an error tells me that the libs are already installed when running in docker. Something must be unclean, but regardless I also think the `reinstall-libs` is a reasonable default, so here we go.
=> opam install with 'reinstall-libs'

scripts/install
I'm assuming that just `make install` installs the `pfff` executable but not libraries. Please correct me as needed.
=> Add 'make reinstall-libs' to install script used by Dockerfile and CircleCI.

lang_go/analyze/go_to_generic.ml, lang_go/analyze/highlight_go.ml, lang_go/analyze/resolve_go.ml, lang_go/parsing/ast_go.ml, lang_go/parsing/parser_go.mly, lang_go/parsing/visitor_go.ml
The goal is to make it easier to have package pattern in semgrep and
to use ast_go.ml for tree-sitter-go
This should help https://github.com/returntocorp/semgrep/issues/1315
Test plan:
make test
=> Refactor Go toplevel declaration

h_program-lang/AST_generic.ml, lang_go/analyze/go_to_generic.ml, tests/go/parsing/assign_vs_shortvar.go
This will help https://github.com/returntocorp/semgrep/issues/1300
Test plan:
You can see below Assign vs AssignOp now
```
+ /home/pad/pfff/pfff -dump_ast assign_vs_shortvar.go
[(DirectiveStmt (Package ((), [("foo", ())])));
(DefStmt
({ name = ("main", ()); attrs = [];
info =
(FuncDef
{ fparams = []; frettype = None;
fbody =
(Block
((),
[(ExprStmt (
(Assign (
(Id (("a", ()),
)),
(), (L (Int ("2", ()))))),
()));
(ExprStmt (
(AssignOp (
(Id (("b", ()),
)),
(Eq, ()), (L (Int ("2", ()))))),
()))
],
()))
})))
]
```
=> Generate different generic AST for x = a, and x := a in Go

h_program-lang/Error_code.ml, h_program-lang/Error_code.mli
This should help https://github.com/returntocorp/semgrep/issues/1361
by giving better diagnoistic when something takes too long in semgrep
Test plan:
make test
=> Add more information in Error_code.Timeout and add Error_code.OutOfMemory

lang_go/parsing/parser_go.mly
Added matching to package under item in order to match "package" keyword in go.
=> Go package bug

lang_python/parsing/Parser_python.mly, tests/python/parsing/fstrings_self_documenting.py
Adds ability to support f"{foo=}".
Note that this adds a wrapping of all f-string interpolants, even
without formatters. So previously:
f"{foo}"
would result in
InterpolatedString([E(Id("foo"))])
and now one gets
InterpolatedString([InterpolatedString([E(Id("foo"))])])
However, as an advantage, wrapping is the same whether or not
a formatter is added.
Fixes returntocorp/semgrep#1339.
=> Add support for self-documenting python 3.8 fstrings

lang_java/parsing/parser_java.mly, tests/java/semgrep/package.sgrep
Fixes returntocorp/semgrep#1381
=> Allow Java package declarations as semgrep patterns

lang_go/analyze/go_to_generic.ml
…Ids. This will change the tuples that structs are converted to to ArgKwds, which match without order.
=> Go Struct Ordering Changes

lang_go/parsing/ast_go.ml, lang_go/parsing/parser_go.mly
Parse_go_tree_sitter.ml needs also those helpers
test plan:
make test
=> Move AST builders helpers from parser_go.mly in ast_go.ml to be reused

lang_go/parsing/Makefile, lang_go/parsing/parser_go.mly, scripts/check_menhir_conflicts.sh, scripts/check_ocamlyacc_conflicts.sh
This will help fix https://github.com/returntocorp/semgrep/issues/1370
test plan:
in semgrep-core test repo:
~/pfff/pfff -lang go -dump_pattern misc_exprstmt_vs_expr.sgrep
(E
(Call ((IdSpecial ((Op Eq), ())),
((),
[(Arg
...
we now have an E (for expr) instead of an S (for stmt)
=> Convert stmt pattern in expr pattern when ExprStmt

lang_js/parsing/parse_js.ml, lang_js/parsing/parser_js.mly
this will help https://github.com/returntocorp/semgrep/issues/1441
Test plan:
test file in semgrep but:
~/pfff/pfff -lang js -dump_pattern misc_jsx.sgrep
(E
(Xml
{ xml_tag = ("div", ());
xml_attrs =
[(("a", ()),
(Call (
(Id (("foo", ()),
)),
((), [], ()))))
];
xml_body = [] }))
=> Parse correctly JSX patterns in semgrep mode

lang_python/analyze/Python_to_generic.ml, lang_python/parsing/AST_python.ml, lang_python/parsing/Parser_python.mly, lang_python/parsing/Visitor_python.ml
This gets closer to the annotation type in AST generic.
This is necessary for https://github.com/returntocorp/semgrep/issues/1508
otherwise we get regressions on python semgrep tests.
test plan:
make
=> More precise type for Python decorator

lang_GENERIC/parsing/Visitor_AST.ml, tests/GENERIC/typing/EqVarCmp.java
A VarDef with an initializer can be expanded as a simple variable
declaration followed by an assignment.
In order to match properly, we must therefore traverse the assignment
_as an expression_. Currently, we visit statements and expressions
separately. To match on this assignment expression then, we must visit
it using Visitor_AST.
I've tested this in semgrep-core (separate commit to follow).
It makes the following match work:
Pattern:
```
foo = "a"
```
Code:
```js
const foo = "a";
```
which previously failed.
This commit also fixes a number of TODO items in the semgrep test
corpus.
=> Visit assignment expression in vardef

.circleci/config.yml, Makefile, lang_ruby/analyze/il_ruby_build.ml, semgrep.yml
Now that semgrep and pfff can correctly parse 100% of pfff codebase,
we can switch to --strict
test plan:
make check
=> Use --strict for semgrep CI

lang_js/analyze/ast_js_build.ml
We do not transpile patter in JS in Parse_javascript_tree_sitter.ml
so we should not do it either in pfff otherwise the semgrep
pattern AST has one shape and the code AST has anohter one
test plan:
make test
=> * lang_js/analyze/ast_js_build.ml: do not transpile pattern anymore

lang_java/parsing/parser_java.mly, tests/java/semgrep/ellipsis-interface.sgrep
This should fix https://github.com/returntocorp/semgrep/issues/877. I have tested it locally (seems to work) and I'll add a test to semgrep in a separate pull request.
=> java: Allow `...' in the body of an interface

lang_go/parsing/parser_go.mly
For issue "Package" in go not working with ellipses. #1569
=> package ellipsis fix

lang_js/parsing/dune, lang_js/parsing/parse_js.ml, ppx/dune, ppx/ppx_profiling.ml
test plan:
make
make test
semgrep-core -profile -e 'FOO' /path/to/foo.js correctly shows
Parse_js.tokens in the profile :)
=> New [@@profiling] PPX extension to cleanup use of Common.profile_code

lang_ruby/analyze/il_ruby_build.ml, lang_ruby/analyze/ruby_to_generic.ml, lang_ruby/parsing/ast_ruby.ml, lang_ruby/parsing/lexer_ruby.mll, lang_ruby/parsing/parser_ruby.dyp, lang_ruby/parsing/parser_ruby.mli, lang_ruby/parsing/parser_ruby_helpers.ml, lang_ruby/parsing/parser_ruby_helpers.mli
The atom and string_kind types are messy, with the wrap at the wrong
place. This is the first part in a series to clean this.
test plan:
make
make test
=> Start of changes to ast_ruby.ml to better represent atoms and strings

lang_ruby/analyze/il_ruby_build.ml, lang_ruby/analyze/ruby_to_generic.ml, lang_ruby/parsing/ast_ruby.ml, lang_ruby/parsing/parser_ruby.dyp, lang_ruby/parsing/parser_ruby_helpers.ml
This is part of a series of PRs to fix the mess on how strings
are represented in Ruby.
This should help https://github.com/returntocorp/semgrep/issues/1609
test plan:
make test
=> Adding wrap on StrChars

commons/Common.ml, commons/Common.mli
The alarm(1) syscall, which Common.timeout_function uses
supports only entire seconds. This new function use itimer which
can have microseconds granularity.
test plan:
make
used in semgrep, see other PR.
=> commons/Common.ml: new timeout_function_float

lang_GENERIC/analyze/Constant_propagation.ml
A variable can be considered "final" when it's assigned just once
(i.e., `!stats.lvalue = 1`). And a variable that is used just once
(i.e., `!stats.rvalue = 1`) may still not hold a constant value.
Probably a typo?
=> generic: Fix bug in constant propagation for Python

lang_ml/analyze/ml_to_generic.ml
Without this, a pattern like let $F ... = ... will
only match function with one parameter.
test plan:
see semgrep related PR
=> * lang_ml/analyze/ml_to_generic.ml: Generate ParamEllipsis when param is an ellipsis

h_program-lang/Parse_info.ml, tests/js/parsing/windows_weird_cr.js
This fixes https://github.com/returntocorp/enterprise/issues/377
test plan:
=> Fix weird parsing error in old JS files for windows

lang_js/analyze/ast_js.ml, lang_js/analyze/js_to_generic.ml
This will help https://github.com/returntocorp/semgrep/issues/1691
test plan:
test file included in related semgrep PR.
Using misc_arrow2.js in semgrep repo below you can now see
a VarDef instead of a FuncDef when the arrow is stored in a var.
+ /home/pad/semgrep/_build/default/bin/Main.exe -dump_ast misc_arrow2.js
Pr(
[DefStmt(
({name=("a", ()); attrs=[KeywordAttr((Const, ()))]; tparams=[];
info={id_resolved=Ref(None); id_type=Ref(None);
},
FuncDef(
{fparams=[]; frettype=None;
fbody=Block([Return((), Some(L(Float(("1", ())))))]); })));
DefStmt(
({name=("a", ()); attrs=[KeywordAttr((Const, ()))]; tparams=[];
info={id_resolved=Ref(None); id_type=Ref(None);
},
FuncDef(
{fparams=[]; frettype=None;
fbody=Block([Return((), …
=> Do not consider lambdas in a var as a function

h_program-lang/AST_generic.ml, h_program-lang/Parse_info.ml, h_program-lang/Visitor_AST.ml, lang_GENERIC/analyze/AST_to_IL.ml, lang_GENERIC/analyze/lrvalue.ml, lang_GENERIC/parsing/Map_AST.ml, lang_GENERIC/parsing/Meta_AST.ml, lang_go/analyze/go_to_generic.ml, lang_ml/analyze/ml_to_generic.ml, lang_php/analyze/foundation/php_to_generic.ml, lang_python/analyze/Python_to_generic.ml, lang_ruby/analyze/ruby_to_generic.ml
This will allow us to return matches on empty tuples,
which currently fails as empty tuples have no
token information.
Adresses returntocorp/semgrep#1654
=> Add bracket info to AST_generic.Tuple
